# Site settings
title: K. Michael Fox
email: kmichaelfox.contact@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  K. Michael Fox is a composer of New Music and an Interactive Multimedia artist.
  He is currently completing a Ph.D. at Rensselaer Polytechnic Institute.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kmichaelfox.com" # the base hostname & protocol for your site
#url: "" # url for local development
twitter_username: kmichaelfox
github_username:  kmichaelfox

# Build settings
permalink: /:categories/:title
markdown: kramdown

safe: true
owner:
  google:
    analytics: UA-68364661-1
